import jsPDF from "jspdf"

export function exportMeetingPDF(
  title: string,
  type: string,
  content: string
) {
  const doc = new jsPDF()

  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()

  const margin = 18
  const maxWidth = pageWidth - margin * 2

  let y = 20

  const addFooter = () => {
    doc.setDrawColor(220)
    doc.line(margin, pageHeight - 15, pageWidth - margin, pageHeight - 15)

    doc.setFont("helvetica", "normal")
    doc.setFontSize(9)
    doc.setTextColor(120)

    doc.text(
      "Generated by IntellMeet AI",
      margin,
      pageHeight - 8
    )

    doc.text(
      `Page ${doc.getNumberOfPages()}`,
      pageWidth - margin,
      pageHeight - 8,
      { align: "right" }
    )
  }

  const checkPage = (space = 10) => {
    if (y + space > pageHeight - 22) {
      addFooter()
      doc.addPage()
      y = 20
    }
  }

  // ===== HEADER =====
  doc.setFillColor(37, 99, 235)
  doc.rect(0, 0, pageWidth, 32, "F")

  doc.setTextColor(255)
  doc.setFont("helvetica", "bold")
  doc.setFontSize(24)
  doc.text("IntellMeet", margin, 15)

  doc.setFontSize(11)
  doc.setFont("helvetica", "normal")
  doc.text("AI Meeting Report", margin, 24)

  y = 45

  // ===== MEETING TITLE =====
  doc.setTextColor(30)
  doc.setFont("helvetica", "bold")
  doc.setFontSize(18)
  doc.text(title, margin, y)

  y += 8

  doc.setFontSize(11)
  doc.setTextColor(100)
  doc.text(type, margin, y)

  y += 8

  doc.setDrawColor(220)
  doc.line(margin, y, pageWidth - margin, y)

  y += 10

  // ===== CONTENT =====

  const lines = content.split("\n")

  lines.forEach((line) => {
    checkPage()

    let text = line.trim()

    if (!text) {
      y += 6
      return
    }

    // Main headings
    if (text.startsWith("# ")) {
      text = text.replace("# ", "")

      y += 4

      doc.setFont("helvetica", "bold")
      doc.setFontSize(18)
      doc.setTextColor(37, 99, 235)

      doc.text(text, margin, y)

      y += 7

      doc.setDrawColor(220)
      doc.line(margin, y, pageWidth - margin, y)

      y += 7

      return
    }

    // Sub headings
    if (text.startsWith("## ")) {
      text = text.replace("## ", "")

      doc.setFont("helvetica", "bold")
      doc.setFontSize(14)
      doc.setTextColor(40)

      doc.text(text, margin, y)

      y += 8
      return
    }

    // Bullet
    if (text.startsWith("- ")) {
      text = "• " + text.substring(2)
    }

    // Remove markdown bold
    text = text.replace(/\*\*/g, "")

    doc.setFont("helvetica", "normal")
    doc.setFontSize(11)
    doc.setTextColor(60)

    const wrapped = doc.splitTextToSize(text, maxWidth)

    wrapped.forEach((row: string) => {
      checkPage()
      doc.text(row, margin, y)
      y += 6
    })
  })

  addFooter()

  doc.save(`${title}-${type}.pdf`)
}